FROM python:3.11-slim
WORKDIR /app
COPY services/teachers/requirements.txt .
RUN pip install -r requirements.txt
COPY services/teachers /app
CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8001"]
